![alt](https://www.unip.br/aluno/central/assets/img/svg/logo-unip.svg)



## Algoritmos de ordenação

In [54]:
import numpy as np
import time
import pandas as pd
import matplotlib as plt


### <li> Bubble Sort </li>

<p> Bubble sort é o algoritmo mais simples, porém menos eficiente.
Cada elemento da posição i será comparado com o elemento da posição i + 1
caso esse elemento (i) for maior que i + 1 eles trocam de lugar. </p>
 

In [58]:
#Algoritmo bubble sort
        
array = np.random.randint(100, size = 10)
print('Array desordenado')
arrayInicial = array
print(array)

print('----------------------------------------------------------')

tempoInicial = time.time()

for passnum in range(len(array)-1,0,-1):
  for i in range(passnum):
    if array[i] > array[i+1]:
      temp = array[i]
      array[i] = array[i+1]
      array[i+1] = temp

tempoFinal = time.time()
tempoExecucao = round(tempoFinal - tempoInicial, 5)


print('Array ordenado em: ' + str(tempoExecucao) + ' segundos')      
print(array)

fig, axis = plt.subplot(1,2)
axis[0,0].plot(arrayInicial, array)
plt.show()

''' df = {'Array desordenado': arrayInicial, 'Array ordenado': array}

fig = px.bar(df, category_orders= df)
fig.show()

fig = px.bar(arrayInicial, title='Array desordenado', color = array)
fig.show()
fig = px.bar(array, title='Array ordenado', color = array)
fig.show() '''

Array desordenado
[67  7 15 54 38 65 14 18 13 67]
----------------------------------------------------------
Array ordenado em: 0.0 segundos
[ 7 13 14 15 18 38 54 65 67 67]


AttributeError: module 'matplotlib' has no attribute 'subplot'

### <li> Selection Sort </li>

<p> Este algoritmo é baseado em se passar sempre o menor valor do vetor para a primeira posição (ou o maior dependendo da ordem requerida), depois o segundo menor valor para a segunda posição e assim sucessivamente, até os últimos dois elementos. </p>

In [ ]:
#Selection Sort
array = np.random.randint(100, size = 10)
print('Array desordenado')
print(array[:10], array[-10:])
print('-----------------------------')

tempoInicial = time.time()

for fillslot in range(len(array)-1, 0, -1):
    positionOfMax = 0
    for location in range(1, fillslot+1):
      if array[location] > array[positionOfMax]:
        positionOfMax = location
    
    temp = array[fillslot]
    array[fillslot] = array[positionOfMax]
    array[positionOfMax] = temp

tempoFinal = time.time()
tempoExecucao = round(tempoFinal - tempoInicial, 5)

print('Array ordenado em: ' + str(tempoExecucao) + ' segundos')  
print(array[:10], array[-10:])

Array desordenado
[44 39 35  3 65 10 53 15 38 46] [44 39 35  3 65 10 53 15 38 46]
-----------------------------
Array ordenado em: 0.0 segundos
[ 3 10 15 35 38 39 44 46 53 65] [ 3 10 15 35 38 39 44 46 53 65]


### <li> Quick Sort </li>

<p> O Quicksort é o algoritmo mais eficiente na ordenação por comparação. Nele se escolhe um elemento chamado de pivô, a partir disso é organizada a lista para que todos os números anteriores a ele sejam menores que ele, e todos os números posteriores a ele sejam maiores que ele. Ao final desse processo o número pivô já está em sua posição final. Os dois grupos desordenados recursivamente sofreram o mesmo processo até que a lista esteja ordenada.  </p>

In [ ]:
#Quick Sort
array = np.random.randint(100, size = 10)
print('Array desordenado')
print(array)
print('-----------------------------')
 

def quickSort(array, inicio, fim):
  if inicio >= fim:
    return
  
  pivo = particiona(array, inicio, fim)
  quickSort(array, inicio, pivo - 1)
  quickSort(array, pivo + 1, fim)

def particiona(array, inicio, fim):
  pivo = array[inicio]
  esquerda = inicio + 1
  centro = fim
  
  while True: 
                        
    while esquerda <= centro and array[centro] >= pivo:
      centro = centro - 1
    
    while esquerda <= centro and array[esquerda] <= pivo:
      esquerda = esquerda + 1
    
    if esquerda <= centro:      
      array[esquerda], array[centro] = array[centro],  array[esquerda]
      
    else:
      break    
    
  #troca
  array[inicio], array[centro] = array[centro], array[inicio]
  return centro

tempoInicial = time.time()
quickSort(array, 0, len(array) - 1)

tempoFinal = time.time()
tempoExecucao = round(tempoFinal - tempoInicial, 5)
print('Array ordenado em: ' + str(tempoExecucao) + ' segundos') 
print(array)
      

Array desordenado
[29 13 41 56 44 88 51 33 39 68]
-----------------------------
Array ordenado em: 0.0 segundos
[13 29 33 39 41 44 51 56 68 88]


### <li> Insertion Sort </li>

<p>O Insertion sort é um algoritmo simples e eficiente quando aplicado em pequenas listas. Neste algoritmo a lista é percorrida da esquerda para a direita, à medida que avança vai deixando os elementos mais à esquerda ordenados. 
O algoritmo funciona da mesma forma que as pessoas usam para ordenar cartas em um jogo de baralho como o pôquer. 
</p>

In [ ]:
#Insertion Sort


array = np.random.randint(100, size = 10)
print('Array desordenado')
print(array)
print('-----------------------------')

tempoInicial = time.time()
for i in range(1, len(array)):
  valorAtual = array[i]
  posicaoAtual = i
  
  while posicaoAtual > 0 and array[posicaoAtual - 1] > valorAtual:
    array[posicaoAtual] = array[posicaoAtual - 1]
    posicaoAtual = posicaoAtual -1
    
  array[posicaoAtual] = valorAtual
  

tempoFinal = time.time()
tempoExecucao = round(tempoFinal - tempoInicial, 5)
  
print('Array ordenado em: ' + str(tempoExecucao) + ' segundos') 
print(array)
  

Array desordenado
[34 19 89 68  5 91 35 98 19 29]
-----------------------------
Array ordenado em: 0.0 segundos
[ 5 19 19 29 34 35 68 89 91 98]
